polls_app/urls.py
from django.urls import path
from . import views

app_name = 'polls_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/vote/', views.vote, name='vote'),
    path('<int:pk>/result/', views.result, name='result'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls_app.urls')),
    path('register/', include('user.urls')),
]

user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('', views.register, name='register'),
]

polls_app/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.

class Question(models.Model):
	question_text = models.CharField('Question', max_length=300)
	pub_date = models.DateTimeField('Published On', default=timezone.now)
	votes_count = models.IntegerField('Votes Count', default=0)

	def __str__(self):
		return self.question_text

	def published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField("Choice", max_length=300)
	votes = models.IntegerField("Votes", default=0)

	def __str__(self):
		return self.choice_text

	# Update "votes_count" field in Question model whenever a Choice is created
	def save(self, *args, **kwargs):
		# print(self.pk)
		if not self.pk:
			Question.objects.filter(pk=self.question_id).update(votes_count=models.F('votes_count') + 1)
		super().save(*args, **kwargs)

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.core.validators import validate_email
from django.contrib import messages

class UserRegistrationForm(UserCreationForm):
	email = forms.EmailField()

	class Meta():
		model = User
		fields = ['username', 'email', 'password1', 'password2']

	def clean(self):
		email = self.cleaned_data.get('email')
		validate_email(email)
		if User.objects.filter(email=email).exists():
		 	raise forms.ValidationError("Email already exists.")
		# try:
		# 	if User.objects.filter(email=email).exists():
		# 	    raise forms.ValidationError("Email exists")
		# except:
		# 	messages.error(request, f'Email already exists.')
		return self.cleaned_data

polls_app/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, redirect
from django.core.paginator import Paginator
from .models import Question, Choice
from django.utils import timezone
from django.db import models
from django.http import HttpResponse

# Create your views here.

def index(request):
	question_list = get_list_or_404(Question.objects.filter(pub_date__lte=timezone.now()).filter(votes_count__gte=2))
	paginator = Paginator(question_list, 3)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)

	return render(request, 'polls_app/index.html', {'page_obj': page_obj })

def detail(request, pk):
	question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()).filter(votes_count__gte=2), pk=pk)

	return render(request, 'polls_app/detail.html', {'question': question})

def result(request, pk):
	question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()).filter(votes_count__gte=2), pk=pk)

	return render(request, 'polls_app/result.html', {'question': question})

def vote(request, pk):
	question = get_object_or_404(Question.objects.filter(pub_date__lte=timezone.now()).filter(votes_count__gte=2), pk=pk)
	try:
		choice = question.choice_set.get(pk=request.POST['choice'])
	except(KeyError, Choice.DoesNotExist):
		context = {
			'question': question,
			'error_msg': "Please select a choice.",
		}

		return render(request, 'polls_app/detail.html', context=context)

	else:
		Choice.objects.filter(pk=choice.id).update(votes=models.F('votes') + 1)
		return redirect('polls_app:result', pk=question.id)
		# return HttpResponse('<h2>Thanks for taking the poll.</h2>')

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegistrationForm
from django.contrib import messages

# Create your views here.

def register(request):
	if request.method == 'POST':
		reg_form = UserRegistrationForm(request.POST)
		if reg_form.is_valid():
			reg_form.save()
			username = reg_form.cleaned_data.get('username')
			messages.success(request, f'Account created for { username }')
			return redirect('polls_app:index')
	else:
		reg_form =  UserRegistrationForm()
	return render(request, 'user/register.html', {'reg_form': reg_form})

polls_app/templates/polls_app/base.html
{% load static %}

<!DOCTYPE html>
<html>
	<head>
		<!-- Required meta tags -->
	    <meta charset="utf-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	    <!-- Bootstrap CSS -->
	    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	    <link rel="stylesheet" type="text/css" href="{% static 'polls_app/base.css' %}">
		<title>Polls App</title>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg navbar-light bg-light p-3 pd-lr border-bottom shadow-sm px-md-4 mb-3">
			<a class="navbar-brand" href="/polls/">Polls</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse justify-content-end" id="navbarNav">
				<ul class="navbar-nav">
					<li class="nav-item active">
						<a class="nav-link 	text-dark" href="#">Home <span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark" href="#">Our Team</a>
					</li>
					<li class="nav-item">
						<a class="nav-link text-dark" href="#">About</a>
					</li>
					<li class="nav-item">
						<a class="btn btn-outline-primary" href="{% url 'user:register'%}" tabindex="-1" aria-disabled="true">Sign up</a>
					</li>
				</ul>
			</div>
		</nav>
		<!-- <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-light border-bottom shadow-sm pd-lr">
	    <h5 class="my-0 mr-md-auto font-weight-normal">Polls</h5>
	    <nav class="my-2 my-md-0 mr-md-3">
	      <a class="p-2 text-dark" href="#">Home</a>
	      <a class="p-2 text-dark" href="#">Our Team</a>
	      <a class="p-2 text-dark" href="#">About</a>
	    </nav>
	    <a class="btn btn-outline-primary" href="#">Sign up</a>
	  </div> -->
		<div class="content-container container">
			{% block content %}{% endblock content %}
		</div>
		<!-- <footer class="footer">
	    <div class="container">
	      <span class="text-muted">Home</span>
	      <a class="p-4 p-lr text-dark" href="#">Polls</a>
	      <a class="p-4 p-lr text-muted" href="#">Home</a>
	      <a class="p-4 p-lr text-muted" href="#">Our Team</a>
	      <a class="p-4 p-lr text-muted" href="#">About</a>
	    </div>
	  </footer> -->
	  <!-- Footer -->
		<footer class="page-footer font-small bg-light mtc">

		  <!-- Footer Links -->
		  <div class="container">

		    <!-- Grid row-->
		    <div class="row text-center d-flex justify-content-center pt-5 mb-3">

		      <!-- Grid column -->
		      <div class="col-md-2 mb-3">
		        <h6>
		          <a href="#!">Home</a>
		        </h6>
		      </div>
		      <!-- Grid column -->

		      <!-- Grid column -->
		      <div class="col-md-2 mb-3">
		        <h6>
		          <a href="#!">Our Team</a>
		        </h6>
		      </div>
		      <!-- Grid column -->

		      <!-- Grid column -->
		      <div class="col-md-2 mb-3">
		        <h6>
		          <a href="#!">About</a>
		        </h6>
		      </div>
		      <!-- Grid column -->
		    </div>
		    <!-- Grid row-->
		    <hr class="rgba-white-light" style="margin: 0 15%;">

		    <!-- Grid row-->
		    <div class="row pb-3">

		      <!-- Grid column -->
		      <div class="col-md-12">

		        <div class="mb-5 flex-center d-flex justify-content-center center-item">

		          <!-- Facebook -->
		          <a class="fb-ic">
		            <i class="fab fa-facebook-f fa-lg white-text mr-4"> </i>
		          </a>
		          <!-- Twitter -->
		          <a class="tw-ic">
		            <i class="fab fa-twitter fa-lg white-text mr-4"> </i>
		          </a>
		          <!--Linkedin -->
		          <a class="li-ic">
		            <i class="fab fa-linkedin-in fa-lg white-text mr-4"> </i>
		          </a>
		        </div>

		      </div>
		      <!-- Grid column -->

		    </div>
		    <!-- Grid row-->

		  </div>
		  <!-- Footer Links -->

		  <!-- Copyright -->
		  <div class="footer-copyright text-center py-3">© 2020 Copyright:
		    <a href="#"> Abhishek</a>
		  </div>
		  <!-- Copyright -->

		</footer>
<!-- Footer -->
		<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
	    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
	    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
	    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
	</body>
</html>

polls_app/templates/polls_app/detail.html
{% extends 'polls_app/base.html' %}

{% block content %}
	<h2>{{ question.question_text }}</h2>
	{% if error_msg %}
		<h6>{{ error_msg }}</h6>
	{% endif %}
	<form action={% url 'polls_app:vote' question.id %} method='post'>
		{% csrf_token %}
		{% for choice in question.choice_set.all %}
			<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
			<label for"choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
		{% endfor %}
		<input type="submit" value="Vote">
	</form>
{% endblock content %}

polls_app/templates/polls_app/index.html
{% extends "polls_app/base.html" %}
{% block content %}
	{% if messages %}
		<div>
			{% for msg in messages %}
				<div class="alert alert-{{ msg.tags }}">
					{{ msg }}
				</div>
			{% endfor %}
		</div>
	{% endif %}
	{% if page_obj %}
		<ul>
			{% for question in page_obj %}
				<li><a href="{% url 'polls_app:detail' question.id %}">{{ question.question_text }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No Polls Available.</p>
	{% endif %}

	<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

polls_app/templates/polls_app/result.html
{% extends 'polls_app/base.html' %}
{% block content %}
	<h2>{{ question.question_text }}</h2>
	<ul>
		{% for choice in question.choice_set.all %}
			<li>{{ choice }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
		{% endfor %}
	</ul>

<a href={% url 'polls_app:detail' question.id %}>Vote Again?</a>

{% endblock content %}

user/templates/user/register.html
{% extends 'polls_app/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
	<div class="content-section">
		<form method="post">
			{% csrf_token %}
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">
					Join Today
				</legend>
				{{ reg_form|crispy }}
			</fieldset>
			<div class="form-group">
				<button class="btn btn-primary" type="submit">
					Sign Up
				</button>
				<small class="text-muted ml-3">Have an account?<a href="#">Sign In</a></small>
			</div>
		</form>
		<!--<div class="border-top pt-3">
			<small class="text-muted">
				Already have an account?<a href="#">Sign In</a>
			</small>
		</div>-->
	</div>
{% endblock content %}